# Generated by Django 3.0.8 on 2020-08-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ip_address',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
