# Generated by Django 3.0.8 on 2020-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_join_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ref_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
