# Generated by Django 3.0.8 on 2020-08-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_join_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='slug',
        ),
    ]
