# Generated by Django 3.0.8 on 2020-08-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_remove_join_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='firend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='first_app.Join'),
        ),
    ]
