# Generated by Django 3.0.8 on 2020-08-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_join_firend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='firend',
        ),
        migrations.AddField(
            model_name='join',
            name='firend',
            field=models.ManyToManyField(related_name='_join_firend_+', to='first_app.Join'),
        ),
    ]
