# Generated by Django 3.0.8 on 2020-08-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20200813_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='firend',
        ),
        migrations.AddField(
            model_name='join',
            name='firend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='first_app.Join'),
        ),
    ]
